### ISSUE TITLE
quicklisp faill?

### ISSUE THREAD

**Issue by gassechen** [ralph-schleicher/rs-json#2]
`(ql:quickload :rs-json)`

System "rs-json" not found
   [Condition of type QUICKLISP-CLIENT:SYSTEM-NOT-FOUND]

**Comment by ralph-schleicher** [comment]
Which version of Quicklisp do you have in use?
Should be not older than 2023-06-18. See
```
(ql:dist-version "quicklisp")
```

**Comment by gassechen** [comment]
(ql:dist-version "quicklisp")
"2023-02-15"
