### ISSUE TITLE
`with-object` prints to `*standard-output*` regardless of chosen `serialize` stream (or `nil`)

### ISSUE THREAD

**Issue by Izaakwltn** [ralph-schleicher/rs-json#3]
Printing an assoc list works as predicted, returning a string when `serialize` is given `nil`.

Using `with-object` however, the result is lost to `*standard-output*`, even though `serialize` should return a string (or write to a specified stream).
```
(in-package #:rs-json)

(defun print-alist-case ()
  (serialize nil '((a . 2) (b . 3))))

(defun make-object-case ()
  (with-object
    (object-member 'a 2)
    (object-member 'b 3)))

(defun print-object-case ()
  (serialize nil (make-object-case)))

(defun print-object-stream-case ()
  (let ((s (make-string-output-stream)))
    (serialize s (make-object-case))
    (get-output-stream-string s)))
```

Return, respectively:
```
;; JSON> (print-alist-case)
;; "{\"A\" : 2, \"B\" : 3}"

;; JSON> (make-object-case)
;; {"A" : 2, "B" : 3}
;; NIL

;; JSON> (print-object-case)
;; {"A" : 2, "B" : 3}
;; "{}"

;; JSON> (print-object-stream-case)
;; {"A" : 2, "B" : 3}
;; "{}"
```

**Comment by ralph-schleicher** [comment]
Hmm, maybe the documentation is not clear enough on how to use with-object.  You should use it inside an encode method (see the example in the README file). For the form ‘(serialize nil (make-object-case))’, ‘(make-object-case)’ is evaluated before the serialize function can bind standard output to the actual output stream. And BTW, the result of with-object is the JSON representation of your data, not the Lisp representation. The serialize function expects a Lisp representation as input. Does this make sense to you?

**Comment by Izaakwltn** [comment]
Thank you for the illumination, that makes more sense!
